### ISSUE TITLE
RFS observations in our implementation are not really sets

### ISSUE THREAD

**Issue by eivinasbutkus** [CNCLgithub/GenRFS#12]
What I mean is that `xs = [true, true, false]` is treated differently from `xs = [true, false]`. In practice, MOT masks are not going to be identical, but perhaps for more general applications of GenRFS, it's important to have a better grasp.

**Comment by belledon** [comment]
yes i think one of the fun things about our implementatoin is the abstract of RFS into multi-sets and dropping the traditional naming schema (mbrfs, pmbrfs, birth rate etc...). Any rfs that has more than one epimorphic element supports multisets
